### ISSUE TITLE
Repo todo

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/uredinales-belgium-checklist#1]
* [x] Update shortname to `uredinales-belgium`
* [x] Move data to /data/input
* [x] Use .tsv extension for data
* [x] Add basic README structure
* [x] Add current README info under section Rationale

**Comment by LienReyserhove** [comment]
I generated a `/data/raw` folder instead of `/data/input`.
This can be changed later.
